# -*- coding: utf-8 -*-
"""Generators QRs project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SW6dQ4xz7mI1iy2Pj75t_DMKG2Wd4RDF
"""

!pip install pyqrcode

import pyqrcode

url = "www.youtube.com"
qr_code = pyqrcode.create(url)
qr_code.svg ("QR_Youtube.svg",scale = 8)